### ISSUE TITLE
The model directive expect line break

### ISSUE THREAD

**Issue by anghelvalentin** [TwentyFourMinutes/RazorMinifier#4]
Hello,
I found an issue related to model directive. My cshtml starts with:

```cs
@model PhoneCountryVM

@{ ViewData["Title"] = "Home Page"; }
```

The problem is that the second line continues on the same line with the model directive, causing the following error:
Unexpected literal following the 'model' directive. Expected 'line break'

**Comment by TwentyFourMinutes** [comment]
Mh, any chance that you do have an empty line break between your `@model` and the `@{ ... }`? This is not expected behavior for the current line matching. However I do agree, it would make sense to also include empty lines.

**Comment by TwentyFourMinutes** [comment]
At the moment you should be able to fix this issue by removing the empty line. In a future version you should be able to put that empty line in there again :).

**Comment by anghelvalentin** [comment]
I have removed that empty line between the two commands, but still not working

**Comment by TwentyFourMinutes** [comment]
That's weird, It doesn't seem that I am able to reproduce this. Can you provide a full example as well as the output you get?

**Comment by anghelvalentin** [comment]
```
@model PhoneCountryVM
@{ViewData["Title"] = "Home Page"; }

<div class="text-center">
    <h1 class="display-4">@Model.CountryName</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

<div class="row">
    <div class="col-md-9">

    </div>
    <div class="col-md-3">
        <div class="list-group">
            @foreach (var item in Model.Regions)
            {
<a asp-controller="Phone" asp-action="GenerateForRegion" asp-route-country="@Model.BranchCode" asp-route-region="@item.Prefix" class="list-group-item list-group-item-action">@item.Name (+@item.Prefix)</a>}
        </div>
    </div>
</div>
```


Output
`@model PhoneCountryVM@{ViewData["Title"] = "Home Page"; }<div class="text-center"><h1 class="display-4">@Model.CountryName</h1><p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p></div><div class="row"><div class="col-md-9"></div><div class="col-md-3"><div class="list-group">@foreach (var item in Model.Regions){<a asp-controller="Phone" asp-action="GenerateForRegion" asp-route-country="@Model.BranchCode" asp-route-region="@item.Prefix" class="list-group-item list-group-item-action">@item.Name (+@item.Prefix)</a>}</div></div></div>`

**Comment by TwentyFourMinutes** [comment]
This is really weird, it works like a charm on my end. Which version of RazorMinifier are you running, also whats your VisualStudio version?

**Comment by anghelvalentin** [comment]
Version 2.2.1  Razor Minifier
Visual Studio 2019 16.8,2

**Comment by anghelvalentin** [comment]
I tried to use your minifier on a txt file that contains my code and it's working, but using the visual studio extensions doesn't work.

**Comment by anghelvalentin** [comment]
It is a problem related to line endings, if I set the line ending to be LF, the minfier broke.

**Comment by TwentyFourMinutes** [comment]
Lemme check that real quick.

**Comment by TwentyFourMinutes** [comment]
I am still not able to reproduce this issue on my end, even with the line ending set to LF. Are you required to use LF line-endings?

**Comment by anghelvalentin** [comment]
No. One extension (Format document on save) broke your extension. I disabled that extensions, and it seems it's ok now

**Comment by anghelvalentin** [comment]
I was able to reproduce the problem like this:
1. Have a txt file and set the Line ending to be LF:
https://imgur.com/ee9vLC5

2.Run the cshtml minfier
```
  string text = @"C:\Users\valen\Desktop\Banca de lucru\github\RazorMinifier\src\RazorMinifier\ConsoleApp2\TextFile1.txt";
            string path = @"C:\Users\valen\Desktop\Banca de lucru\github\RazorMinifier\src\RazorMinifier\ConsoleApp2\TextFile2.txt";
            await CSHtmlMinifier.MinifyFileAsync(text, path, false);
```

**Comment by TwentyFourMinutes** [comment]
> Format document on save

You can use [`PowerCommands`](https://marketplace.visualstudio.com/items?itemName=VisualStudioPlatformTeam.PowerCommandsforVisualStudio) instead, it also has a `Format document on save` option.
